---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./filebrowser/ks.yaml
  - ./freshrss/ks.yaml
  - ./glance/ks.yaml
  - ./hypermind/ks.yaml
  - ./it-tools/ks.yaml
  - ./mealie/ks.yaml
  - ./namespace.yaml
  - ./romm/ks.yaml
