server:
  port: 80
  proxied: true
theme:
  background-color: 240 21 15
  contrast-multiplier: 1.2
  primary-color: 217 92 83
  positive-color: 115 54 76
  negative-color: 347 70 65
pages:
  - name: Home
    columns:
      - size: small
        widgets:
          - type: bookmarks
            groups:
              - title: Local Infra Links
                color: 96 44 68
                links:
                  - title: GitOps Repo
                    url: "https://github.com/Stormcargo/k8s-gitops/"
                    icon: sh:kubernetes
                  - title: UniFi UI
                    url: https://unifi.ui.com/
                    icon: di:unifi
                  - title: JetKVM
                    url: "http://jetkvm.relayone.website"
                    icon: di:jetkvm
                  - title: SLZB
                    url: "http://slzb-06.relayone.website"
                    icon: di:smlight

              - title: Home-ops links
                color: 96 44 68
                links:
                  - title: Kubesearch
                    url: "https://kubesearch.dev/"
                    icon: di:searxng
                  - title: Template Chart Docs
                    url: "https://github.com/bjw-s/helm-charts/tree/main/charts/library/common"
                    icon: si:googledocs
                  - title: Flux Docs
                    url: "https://fluxcd.io/flux/"
                    icon: di:flux-cd

      # Middle Wide Column
      - size: full
        widgets:
          - type: split-column
            widgets:
            - type: extension
              url: http://glance-k8s-extension:8080/extension/nodes
              allow-potentially-dangerous-html: true
              cache: 1s
              parameters:
                # namespace, name annotations
                show-if: |
                  namespace != kube-system &&
                  ("glance/hide" not in annotations || annotations["glance/hide"] != "true")
            - type: extension
              url: http://glance-k8s-extension:8080/extension/apps
              allow-potentially-dangerous-html: true
              cache: 1s
              parameters:
                # namespace, name annotations
                show-if: |
                  ("glance/internal" in annotations && annotations["glance/internal"] == "true") &&
                  ("glance/hide" not in annotations || annotations["glance/hide"] != "true")

          # - type: extension
          #   url: http://glance-k8s-extension:8080/extension/nodes
          #   allow-potentially-dangerous-html: true
          #   cache: 1s
          #   parameters:
          #     # namespace, name annotations
          #     show-if: |
          #       namespace != kube-system &&
          #       ("glance/hide" not in annotations || annotations["glance/hide"] != "true")
          # - type: extension
          #   url: http://glance-k8s-extension:8080/extension/apps
          #   allow-potentially-dangerous-html: true
          #   cache: 1s
          #   parameters:
          #     # namespace, name annotations
          #     show-if: |
          #       ("glance/internal" in annotations && annotations["glance/internal"] == "true") &&
          #       ("glance/hide" not in annotations || annotations["glance/hide"] != "true")
      # End Middle Column


      # Right Column
      - size: small
        widgets:
          - type: clock
            hour-format: 12h
            timezones:
              - timezone: Europe/London
                label: London
              - timezone: Australia/Melbourne
                label: Melbs
              - timezone: Europe/Berlin
                label: Germany
          - type: weather
            units: metric
            location:  London, United Kingdom
          - type: repository
            repository: Stormcargo/k8s-gitops
            display: Home Infra
            pull-requests-limit: 3
            issues-limit: 3
      # End Right Column
