server:
  port: 80
  proxied: true
theme:
  background-color: 240 21 15
  contrast-multiplier: 1.2
  primary-color: 217 92 83
  positive-color: 115 54 76
  negative-color: 347 70 65
pages:
  - name: Home
    columns:
      - size: small
        widgets:
          - type: clock
            hour-format: 12h
            timezones:
              - timezone: Europe/London
                label: Time
          - type: calendar

          - type: bookmarks
            groups:
              - title: Home Infra Links
                color: 10 70 50
                links:
                  - title: GitOps Repo
                    url: "https://github.com/Stormcargo/k8s-gitops/"
                    icon: sh:kubernetes
                  - title: UniFi UI
                    url: https://unifi.ui.com/
                  - title: JetKVM
                    url: "http://jetkvm.relayone.website"
                  - title: SLZB
                    url: "http://slzb-06.relayone.website"

      - size: full
        widgets:
          - type: extension
            url: http://glance-k8s-extension:8080/extension/nodes
            allow-potentially-dangerous-html: true
            cache: 1s
            parameters:
              # namespace, name annotations
              show-if: |
                namespace != kube-system &&
                ("glance/hide" not in annotations || annotations["glance/hide"] != "true")
          - type: extension
            url: http://glance-k8s-extension:8080/extension/apps
            allow-potentially-dangerous-html: true
            cache: 1s
            parameters:
              # namespace, name annotations
              show-if: |
                ("glance/internal" in annotations && annotations["glance/internal"] == "true") &&
                ("glance/hide" not in annotations || annotations["glance/hide"] != "true")
          - type: hacker-news

      - size: small
        widgets:
          - type: weather
            units: metric
            location:  London, United Kingdom
          - type: repository
            repository: Stormcargo/k8s-gitops
            display: Home Infra
            pull-requests-limit: 5
            issues-limit: 3
          - type: monitor
            cache: 1m
            title: Services
            style: compact
            sites:
              - title: Home Assistant
                url: https://hass.relayone.website
