---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres17
  namespace: databases
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.7
  primaryUpdateStrategy: unsupervised
  storage:
    size: 40Gi
    storageClass: longhorn-cnpg
  superuserSecret:
    name: cloudnative-pg-secret
  enableSuperuserAccess: true
  resources:
    requests:
      memory: 1.5Gi
    limits:
      memory: 2Gi

  # Bootstrap from scratch initially
  # bootstrap:
  #   recovery:
  #     source: &previousCluster postgres16-v5

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: 512MB

  monitoring:
    enablePodMonitor: true
    # https://github.com/cloudnative-pg/cloudnative-pg/issues/2501
    podMonitorMetricRelabelings:
      - { sourceLabels: [ "cluster" ], targetLabel: cnpg_cluster, action: replace }
      - { regex: cluster, action: labeldrop }

  backup:
    retentionPolicy: "30d"

    barmanObjectStore:
      wal:
        compression: bzip2
        maxParallel: 4
      data:
        compression: bzip2

      serverName:  postgres17-v1
      destinationPath: s3://cloudnative-pg/cnpg
      endpointURL: https://8107775533e1b38958f2bfea727bdef2.r2.cloudflarestorage.com


      s3Credentials:
        accessKeyId:
          name: cloudnative-pg-secret
          key: aws-access-key-id
        secretAccessKey:
          name: cloudnative-pg-secret
          key: aws-secret-access-key

  # Uncomment when you need to recover from backups
  # externalClusters:
  #   - name: postgres17-v1
  #     barmanObjectStore:
  #       wal:
  #         compression: bzip2
  #         maxParallel: 8
  #       destinationPath: s3://cloudnative-pg/postgres17/
  #       endpointURL: https://8107775533e1b38958f2bfea727bdef2.r2.cloudflarestorage.com
  #       serverName: postgres17-v1
  #       s3Credentials:
  #         accessKeyId:
  #           name: cloudnative-pg-secret
  #           key: aws-access-key-id
  #         secretAccessKey:
  #           name: cloudnative-pg-secret
  #           key: aws-secret-access-key
