---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/scheduledbackup_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: daily-backup
  namespace: databases
spec:
  backupOwnerReference: self
  schedule: "0 2 * * *"  # 2 AM daily
  cluster:
    name: postgres17
  method: barmanObjectStore
